### ISSUE TITLE
Error page when deleting a blog from a multisite

### ISSUE THREAD

**Issue by pdewouters** [humanmade/altis-cms#101]
URL wp-admin/network/sites.php?action=deleteblog&updated=delete

Go to the list of sites in the network admin
Click "delete"
Observe as the page seems to ntot respond
Observe the error page
The site is deleted as expected

I would expect to be redirected to the admin instead
<img width="863" alt="Screenshot 2019-09-19 at 16 52 41" src="https://user-images.githubusercontent.com/30460/65260533-673b5200-dafe-11e9-8e41-82fb12be5000.png">

**Comment by roborourke** [comment]
Noticed on Local Server too but with an error message related to not being able to delete the uploads directory.

**Comment by roborourke** [comment]
@pdewouters is this with Local Chassis?

**Comment by kevinlangleyjr** [comment]
This seems to be fixed with the above PR from @roborourke.

**Comment by roborourke** [comment]
Magic! You're quite right, cheers for confirming @kevinlangleyjr
