### ISSUE TITLE
Add performance enhancements for WP

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-cms#104]
Core WP has some performance issues that may only reveal themselves in certain situations. We can start adding some simple mitigations in this module:

- force limit comments per page to 50 maximum
- add https://github.com/Automattic/advanced-post-cache
- add https://github.com/Automattic/lightweight-term-count-update

ht/ @johnbillion 

Acceptance criteria:

- [x] Comment pagination is always enabled
- [x] Impossible set comments per page to a value higher than 50
- [ ] Advanced post cache is required in `composer,json`
- [ ] Advanced post cache file is loaded on the `muplugins_loaded` hook in `inc/namespace.php`
- [ ] Lightweight term count update is required in `composer.json`
- [ ] Lightweight term count is loaded on the `muplugins_loaded` hook in `inc/namespace.php`
- [ ] Above plugins are added to the exclude list in humanmade/altis-core here https://github.com/humanmade/altis-core/blob/master/inc/composer/class-installer.php#L26
- [ ] Review and document performance tweaks from https://github.com/Automattic/vip-go-mu-plugins-built/tree/master/performance here to see what else we could add

**Comment by johnbillion** [comment]
Background:

* Advanced Post Cache caches post queries in regular loops. I've not tested it heavily but it does remove the main post query once the cache is warm.
* Lightweight Term Count Update removes the slow queries that core performs when recalculating the number of posts assigned to terms after updating a post's terms. On the RS DMS project with ~6M rows in the posts table these queries take 20 full seconds for each taxonomy. Notably, this isn't enabled during cron and CLI requests, which is where we were seeing terrible performance problems recently. We enabled it for cron events according to https://github.com/Automattic/lightweight-term-count-update/issues/9.

In addition:

* VIP implements a meta_key+meta_value index on the postmeta table. The index can get 
huge but it does allow for performant meta_value queries, and we're actively using them on RS DMS. https://github.com/Automattic/vip-go-mu-plugins-built/blob/97ee6f2abc79bd1bb5e9149f5d63e5f201d179be/schema.php . Joe H indicated he'd be hesitant about implementing this as-is, but it's certainly something to consider if for some reason ES isn't a viable solution for a particular site.

**Comment by johnbillion** [comment]
VIP has some more performance tweaks here but I've not looked at them in depth: https://github.com/Automattic/vip-go-mu-plugins-built/tree/master/performance

**Comment by dashaluna** [comment]
@roborourke could you point where to add comment limitations please?

**Comment by johnbillion** [comment]
> We enabled it for cron events according to [Automattic/lightweight-term-count-update#9](https://github.com/Automattic/lightweight-term-count-update/issues/9).

Relevant link for enabling LTCU during cron events: https://github.com/wpcomvip/rs-dms/pull/19/files

**Comment by dashaluna** [comment]
Both packages mentioned in the description aren't on packagist.

@rmccue is checking if there are forks/substitutes to use instead. Slack conversation as a ref https://hmn.slack.com/archives/C3CKS8LLR/p1579876532110100

**Comment by roborourke** [comment]
@dashaluna the comment pagination code should go in performance namespace, you should find it under the `inc` directory

**Comment by roborourke** [comment]
@dashaluna sorry! My fault, the code I was thinking of is in the cloud module. In this case you can add the code to the `inc/namespace.php` file.

**Comment by dashaluna** [comment]
@rmccue let me know if there are any updates on those plugins in the description.

**Comment by dashaluna** [comment]
Waiting to see what to do with both plugins as they are not on packagist.

**Comment by roborourke** [comment]
@dashaluna if you have time and want to come back to this you can create issues on the repos to request that they publish them on packagist. We've done that before.

**Comment by dashaluna** [comment]
Post cache: https://github.com/Automattic/advanced-post-cache/issues/19
Lightweight term count: https://github.com/Automattic/lightweight-term-count-update/issues/18

**Comment by roborourke** [comment]
Closing out in favour of #207 and #206
