### ISSUE TITLE
No Favicon in WP Admin

### ISSUE THREAD

**Issue by tomjn** [humanmade/altis-cms#112]
<img width="71" alt="Screenshot 2019-10-11 at 16 29 28" src="https://user-images.githubusercontent.com/58855/66664373-50db6e80-ec44-11e9-81da-dffcfc894181.png">
WP Admin and the frontend have no favicon by default, there should be a default favicon with an Altis logo for the back end

---------

Acceptance criteria:

- [ ] Favicon defaults to Altis favicon if not set

**Comment by rmccue** [comment]
Is there a reason we should include this? This is without a doubt going to be customised on every site, so not sure we should bother.

**Comment by tomjn** [comment]
Oh I agree, especially on the frontend, but it's a polish thing. When you first fire up a local environment it has the default which is suboptimal.

We should be able to plug into cores site icon functionality and provide an altis logo as a fallback for when nothing has been specified in the admin area. I don't know that i'd be comfortable doing that on the frontend though

**Comment by rmccue** [comment]
Should we make the favicon in the admin always be the Altis logo? @grarighe (cc @noeltock)

**Comment by noeltock** [comment]
@Camila-villegas When you get a chance, can you throw something quick together?
- Start with 512x512
- Requires transparency
- Can test here https://favicon.io/favicon-converter/

Thank you!

**Comment by joehoyle** [comment]
Could we just use the one from altis-dxp.com ?

**Comment by Camila-villegas** [comment]
Forwarding you guys the one we have been using:  https://drive.google.com/open?id=1-2oIQ3ZNy6UvAC9xF6aqwwJwc2llkahM

**Comment by robindevitt** [comment]
Similar to how the login logo is set, should the favicon be managed through the the `config` file too?

**Comment by robindevitt** [comment]
[PR](https://github.com/humanmade/altis-cms/pull/483) is ready for review, requested from Rob or Shadi.

**Comment by robindevitt** [comment]
Rob got a couple changes done and closed the issue out.
