### ISSUE TITLE
Remove default user colour schemes

### ISSUE THREAD

**Issue by tomjn** [humanmade/altis-cms#113]
When using the light colour scheme in WP Admin, the Altis logo is barely visible

<img width="265" alt="Screenshot 2019-10-11 at 16 30 18" src="https://user-images.githubusercontent.com/58855/66664469-81230d00-ec44-11e9-9b6b-4c01cab60aee.png">

-----------------

Acceptance criteria:

- [x] unregister default WP admin colour schemes (unless option is already set if possible)
- [x] must allow new custom schemes to be registered
- [x] document how to add a custom colour scheme for accessibility purposes

Optional / extra credit :)

- [ ] add a built in accessible colour scheme
- [ ] ability to enable colour scheme via config, off by default
- [ ] document enabling the colour scheme

**Note**: moved the environment indicator feature to the cloud module https://github.com/humanmade/altis-cloud/issues/124

**Comment by rmccue** [comment]
cc @grarighe do we have a dark logo we could use here?

Alternatively, we could disable the light scheme altogether (see previous discussion around colour schemes).

**Comment by tomjn** [comment]
An translucent outline on the word Altis could do the trick in unforeseen circumstances, it's rare that additional light schemes get created though

**Comment by grarighe** [comment]
We do, but to tie in with our design principles, we discussed disabling the colour scheme options, which makes this scenario even more of an edge case, if I understood correctly. I guess we _could_ make it work, but up to you and the PO @rmccue.

**Comment by rmccue** [comment]
Previously: https://github.com/humanmade/altis-cms/pull/30

Let's discuss this again.

**Comment by roborourke** [comment]
So full circle, we'll remove user colour schemes and add a tool to differentiate the environments. I have updated the original comment with acceptance criteria.

**Comment by roborourke** [comment]
@dashaluna this one is a bit meatier but should be ok, let me know when you get to the environment indicator and we can work out the design of it after the underlying code is done.

**Comment by dashaluna** [comment]
@roborourke can I clarify the fist one?
> unregister default WP admin colour schemes (unless option is already set if possible)

so if a user has already selected a non Altis colour theme, we should keep it as is and un-register all other WP supplied ones. I.e. there will be just 2 options: Altis and the currently selected one. Is that correct?

**Comment by roborourke** [comment]
> i.e. there will be just 2 options: Altis and the currently selected one. Is that correct?

Yeah, just to avoid any surprises.

**Comment by dashaluna** [comment]
@roborourke re
>  document how to add a custom colour scheme for accessibility purposes
are we talking about adding colour scheme programatically? Don't think we can do it in WP sidebar with some settings?

**Comment by dashaluna** [comment]
re https://github.com/tomjn/Local-Indicator plugin. It adds the following info to the `wp admin bar` (if one is active and a user has capabilities to see it):

<img width="931" alt="Screenshot 2020-01-29 16 33 27" src="https://user-images.githubusercontent.com/2185972/73377709-5cb47480-42b7-11ea-98f4-bc79fcb8edc9.png">

In our case I wonder what info and where should we display per environment? Does wp admin bar is a good place? Also what colours to use per environment?

**Comment by tomjn** [comment]
I wrote that plugin quite a while ago, I'm pretty sure there's some refinement and improvement that can be made. Perhaps something next to the altis logo? It need not have the submenu of local indicator.

There are other plugins that change the entire toolbar colour, and I've added top borders to the admin bar in the past for differentiation across sites.

There's also the question of what is being differentiated? Local vs non-local? Production vs preprod?

To be fair I never considered environment indicators when opening this issue

**Comment by roborourke** [comment]
@dashaluna I moved that specific feature to the cloud module in this issue as it makes more sense there https://github.com/humanmade/altis-cloud/issues/124

In terms of the design implementation lets discuss it further on that issue.

@tomjn for reference there was further discussion on https://github.com/humanmade/platform-dev/issues/419

To keep things simple for us it'll be easiest to remove those other colour schemes but allow the addition of custom ones. A core value add of using different colour schemes was to differentiate the current environment so we're making sure that's accounted for.

**Comment by tomjn** [comment]
well I've an itch to scratch now to improve that plugin, if only so it shows on wp.org again

**Comment by roborourke** [comment]
@tomjn that be sweet if you have time, appreciate your input on how it could look for Altis. This is really distinguish environment _type_ in our case

**Comment by roborourke** [comment]
@dashaluna re:

> Are we talking about adding colour scheme programatically? Don't think we can do it in WP sidebar with some settings? A bit unclear what approach of adding a colour scheme needs to be documented.

Sorry for not making this clearer, it's a built in piece of WP functionality, so yes, it's only about adding a colour scheme programmatically. See here for reference:

https://developer.wordpress.org/reference/functions/wp_admin_css_color/

**Comment by dashaluna** [comment]
@roborourke I wonder we need to create an issue for `add a built in accessible colour scheme` sounds like a good thing to do, so it's not gonna forgotten but be visible with low priority? I thought I'd flag it :)

**Comment by roborourke** [comment]
@dashaluna yep, good shout. Can you add it with the acceptance criteria from the top comment?
