### ISSUE TITLE
Altis Admin Bar Frontend Spacing

### ISSUE THREAD

**Issue by tomjn** [humanmade/altis-cms#115]
On the frontend the Altis admin bar logo has full WP Admin spacing, despite there being no admin bar:

<img width="438" alt="Screenshot 2019-10-11 at 16 34 58" src="https://user-images.githubusercontent.com/58855/66664772-16260600-ec45-11e9-99c0-161ea13e2f72.png">

It looks as if an item is present but hidden or missing

**Comment by tomjn** [comment]
First thoughts on wrangling this would be to have the CSS work from a collapsed by default viewpoint, then override for when the admin body class is present, and again for folded, but there's probably a simpler set of rules to do it

**Comment by kevinlangleyjr** [comment]
Should we only be targeting the frontend with this styling change?

I personally think even in the backend it looks better to have the rest of the admin bar right next to the Altis logo.

**Current**
![Screen Shot 2020-01-09 at 1.10.02 PM.png](https://images.zenhubusercontent.com/544ec2c47c6ccc6277a58b71/bb6f3787-bed0-4a50-a218-b75b36854923)

**Proposed**
![Screen Shot 2020-01-09 at 1.09.25 PM.png](https://images.zenhubusercontent.com/544ec2c47c6ccc6277a58b71/ad6f788d-5fdd-447c-9c34-9f9ecb6e2b75)

**Comment by sambulance** [comment]
PR: #175

**Comment by roborourke** [comment]
It was an explicit decision to do that yeah. Thanks for fixing it on the front end Sam!
