### ISSUE TITLE
Altis Admin bar button leads nowhere

### ISSUE THREAD

**Issue by tomjn** [humanmade/altis-cms#116]
The button doesn't do anything, and has a normal mouse cursor, which implies broken anchor markup, instead it should lead somewhere useful, such as the About page as standard WP would:

![IMG_3737](https://user-images.githubusercontent.com/58855/66665079-af551c80-ec45-11e9-94ce-5c5af65392d8.JPG)

**Comment by roborourke** [comment]
> The button doesn't do anything, and has a normal mouse cursor, which implies broken anchor markup

I'd argue that it's just not a link, if the cursor was a pointer and it didn't go anywhere then it'd be more of an issue. There are some top level items like that in the admin bar added by some plugins, they just happen to be styled with the same hover effects.

If we do link it I don't think the About page is the right target, it's not something I'd ever be checking often enough to warrant having such a prominent link to it. I'd argue that the docs or the dashboard would be a more sensible target if anything.

Thoughts @kevinlangleyjr @tomjn ?

**Comment by tomjn** [comment]
I like the docs/dashboard as a target, dashboard sounds more practical

**Comment by kevinlangleyjr** [comment]
I think the dashboard makes sense to me 👍
