### ISSUE TITLE
Apply Altis styling to QM

### ISSUE THREAD

**Issue by tomjn** [humanmade/altis-cms#117]
The styling doesn't match, but it would look significantly better if it did:

<img width="377" alt="Screenshot 2019-10-11 at 16 50 04" src="https://user-images.githubusercontent.com/58855/66665815-39ea4b80-ec47-11e9-9e93-2aca9c688919.png">

A few adjustments make a big difference:

<img width="337" alt="Screenshot 2019-10-11 at 16 52 00" src="https://user-images.githubusercontent.com/58855/66665944-7cac2380-ec47-11e9-9356-9a0d7f8a3412.png">

**Comment by grarighe** [comment]
I think the text in 'Overview' also has some WP blue shadow, we need to check it and remove it if that's the case.

**Comment by tomjn** [comment]
All the links in thagt panel are WP blue too, it needs a proper check and walk through
