### ISSUE TITLE
Add a fields component eg. CMB2 / Fieldmanager

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-cms#15]
Fields / meta boxes and options pages are common requirements for any project and inhernetly tied to the CMS. I propose we bundle either CMB2 or Fieldmanager with the CMS module.

General feedback I've heard so far:

- Fieldmanager is more powerful / extensible
- CMB2 is prettier

Would be good to get thoughts of the wider engineering team on this too.

**Comment by joehoyle** [comment]
OH yeah, I was going to write an RFC for this, I feel like it might be a big enough decision to use the RFC process

**Comment by roborourke** [comment]
Sure makes sense 👍

**Comment by jennybeaumont** [comment]
RFC in progress https://github.com/humanmade/platform-dev/pull/330
Closing until further scoping has been done
