### ISSUE TITLE
Add guidance on DNS to add site UI

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-cms#150]
It might be a good idea for us to add information about how and where to provide DNS records when choosing the custom domain option.

Given I am creating a new site in the New Sites screen
When I select Custom Domain
Then I should be given a prompt noting that DNS must be set up before the domain will work

Suggested text:
> Note: Custom domains may require DNS records to be added before they can be used. [Contact support](https://dashboard.altis-dxp.com/#/support) for further details about the required records if needed.

**Comment by roborourke** [comment]
Can you add the info on how and where to do that to this issue?

**Comment by rmccue** [comment]
@roborourke sorry, updated
