### ISSUE TITLE
Allow sites to override WordPress version.

### ISSUE THREAD

**Issue by peterwilsoncc** [humanmade/altis-cms#166]
For sites using the Altis infrastructure, it's understandable the Altis team would like to fully review WordPress upgrades before allowing them on the systems.

Sites using the Altis open-source projects on non-Altis infrastructure may wish to run the site in cowboy mode and upgrade WordPress on their own schedule. It would be helpful if the WordPress version could be upgraded in these instances.

In composer it's possible to specify one package version to override a sub-packages preferences but the need for exact version prevents the use of `5.3.x` or similar.

**Comment by joehoyle** [comment]
Hmm I think there is a way to do it form the root composer.json still, @roborourke can a snippet I think? I don't think we want this as part of the official docs, but maybe @roborourke can share here.

**Comment by roborourke** [comment]
@peterwilsoncc i think you can use the replaces property of composer.json to specify the WP installer package, then require it directly at the version you want

**Comment by peterwilsoncc** [comment]
Including `johnpbloch/wordpress` in both `require` and `replace` failed as replace prevents the package installed. This is how I worked around it testing against Altis 2.

```
"require": {
  // Altis stuff.
  "johnpbloch/wordpress-core-installer": "^1.0",
  "johnpbloch/wordpress-core": "5.3.*"
},
"replace": {
  "johnpbloch/wordpress": "5.2.*"
}
```

I totally understand why you may not wish to make this an official feature so closing this off.
