### ISSUE TITLE
Add Site UI requires logic checks for URL parsing,

### ISSUE THREAD

**Issue by peterwilsoncc** [humanmade/altis-cms#167]
Testing the Add site UI locally, I entered `peterwilsonme.local/~` as a custom domain, as I neglected the scheme a few undefined variable and index notification were thrown.

![peterwilsoncc_local_wp-admin_network_site-new_php](https://user-images.githubusercontent.com/519727/71648454-7e721880-2d58-11ea-9bd7-d79e1b9400fc.jpg)

**Comment by sambulance** [comment]
I wasn't able to replicate this locally - @peterwilsoncc can you share details of your setup please? A screenshot of /wp-admin/about.php and if you're using Chassis/Docker would be useful.

**Comment by peterwilsoncc** [comment]
@sambulance 

Sorry, looks like I had the report backward and the error came up from including the scheme as `$url` is undefined, see https://3v4l.org/C2rmq

It looks like the fix is:

```diff
-function handle_custom_domain( string $value ) : ?array {
+function handle_custom_domain( string $url ) : ?array {
```
