### ISSUE TITLE
Add extended custom post types

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-cms#17]
https://github.com/johnbillion/extended-cpts

Just as a basic value add to the CMS, it's a really smart and useful way to add post types and customise admin menus.

Will need some documentation for the basic usage, can be copy pasted to some extent from @johnbillion's repo.

**Comment by kadamwhite** [comment]
New-contributor question: What would "including" this look like? I'm a little unclear on where things go, still.

**Comment by roborourke** [comment]
Good point! I should document that on the main dev repo. In the meantime however this means:

- require the library as a composer dependency of this package
- add a loading function to the inc/namespace.php file like the one that loads user signups
- hook the loading function up in the bootstrap function in the above file
- optionally add a config setting in load.php for whether to load it or not (probably not necessary in this instance)
- document the new functionality, it doesn’t have to be as detailed as the library’s own docs. Just list the register_* functions and provide an example or two for each

**Comment by joehoyle** [comment]
Also an exception for any `type: wordpress-plugin` etc needs to be added to https://github.com/humanmade/altis-core/blob/master/inc/composer/class-installer.php#L46 to make sure the plugin is installed into the `vendor` directory.

**Comment by johnbillion** [comment]
Note that ExtendedCPTs isn't a plugin, it's a library with composer autoloading support so you shouldn't need to mess with installation paths etc.
