### ISSUE TITLE
Nonce name conflict on Add New Site screen

### ISSUE THREAD

**Issue by kucrut** [humanmade/altis-cms#203]
The [nonce field](https://github.com/humanmade/altis-cms/blob/97c921a606421e19d33fa7d8cf37664853141faa/inc/add_site_ui/namespace.php#L70) on Add New Site screen is using the default name `_wpnonce` which could cause conflict with other plugins that is also adding a nonce field with default name. This prevents new site from being created without _any_ error message.

-----------

Acceptance criteria:

- [ ] The default nonce name on the add new site screen is changed to `_altis_add_site_nonce`
- [ ] The add new site screen continues to function as intended

**Comment by rmccue** [comment]
This nonce field replaces core's, so I think it's *meant* to be the default key. Seems like the issue would be a plugin adding additional fields and using that nonce key?

**Comment by roborourke** [comment]
Yeah, ideally if a plugin is extending that screen it should use a namespaced nonce name anyway. We could always do the same in Altis but this should be updated in the plugin in the meantime too.
