### ISSUE TITLE
Add configuration option to disable feeds

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-cms#205]
By default WordPress exposes feeds for public content. This is not obviously exposed anywhere.

We should add a configuration option to disable feeds, and document it, making it clear that this data is exposed. Note that we do not want to change the default at this time.

Acceptance criteria:
* [ ] When I set `modules.core.remove-feeds` to true in the Altis config, feeds should be disabled
* [ ] When I set up a new Altis installation, feeds should be enabled
* [ ] When I view the CMS documentation, I should be able to clearly see how to configure this option and what the default is

**Comment by ivdimova** [comment]
@rmccue according to the first check, shouldn’t this be in `modules.cmc.remove-feeds`? And also `removes-feeds` set to false to disable feeds doesn't seem logically ok to me. I am attaching PR, please review and let me know. I am not sure we need to also remove the comments rss and the links in the headers but I've read it's the better approach.
