### ISSUE TITLE
Add Lightweight Term Count Update plugin

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-cms#206]
Add https://github.com/Automattic/lightweight-term-count-update plugin.

This is blocked by a8c not having published the package to packagist yet.

Acceptance criteria:

- [ ] Lightweight term count update is required in `composer.json`
- [ ] Lightweight term count is loaded on the `muplugins_loaded` hook in `inc/namespace.php`
- [ ] Above plugin is added to the exclude list in humanmade/altis-core here https://github.com/humanmade/altis-core/blob/master/inc/composer/class-installer.php#L26

**Comment by PriyaBhatia0210** [comment]
Blocked by upstream

**Comment by johnbillion** [comment]
Related: https://core.trac.wordpress.org/ticket/40351 (not currently milestoned)

**Comment by roborourke** [comment]
Lets drop this in favour #467
