### ISSUE TITLE
Swap WP admin bar menu item

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-cms#21]
We should swap this default WP menu item:

<img width="166" alt="Screenshot 2019-04-09 11 28 37" src="https://user-images.githubusercontent.com/23417/55793694-70d67d80-5abb-11e9-8ddf-68794c9ac49f.png">

For one with our logo and following links:

- our site
- docs (local only)
- cloud (super admin only)
- dashboard (vantage)

**Comment by joehoyle** [comment]
Added the menu item in #27. PR pending for the docs addition.

**Comment by rmccue** [comment]
Closing this out; we have better/more specific tickets for the individual things that need to be done here.
