### ISSUE TITLE
Dependabot isn't PRing wp updates on version branches

### ISSUE THREAD

**Issue by joehoyle** [humanmade/altis-cms#223]
At the moment, dependable is just PRing updates to the `master` branch, which means when there is a WordPress patch release, we don't necessarily get it backported, if `master` has a new major version of wordpress.

Instead I think we want dependabot to PR against all our support `vX-branch` branches for their respective version of WordPress. 

The same probably applies to all deps, but WP is the most prominent.

**Comment by roborourke** [comment]
Is that because the version constraint is fixed?

**Comment by joehoyle** [comment]
I think we neee multiple dependable confit blocks, or something, specifying different based branches

--

Joe Hoyle

CTO
Human Made

**Comment by roborourke** [comment]
Fixed using native dependabot but we have to add new branches to the config on each new release and when a release goes out of LTS.
