### ISSUE TITLE
Add real GUIDs

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-cms#229]
Default GUIDs in WordPress are based off the current site URL and are generally a poor indicator of uniqueness when you factor in migrations and the potential for breakages on search / replace operations etc...

We should switch to generating real GUIDs for posts (WP even has a built in function for this now).

This change won't affect existing content and will only apply to new content.

@rmccue has a plugin here https://github.com/rmccue/realguids

----------------------------

Acceptance criteria:

- [ ] Create a new namespace folder and file under `inc` and include in the `composer.json` autoload files section
- [ ] Copy the filters from the plugin code linked above into a setup function
- [ ] Call the setup function from the CMS module set up function
- [ ] Replace the linked plugin's `generate_uuid()` function with the built in `wp_generate_uuid()`

**Comment by rmccue** [comment]
That plugin can also be simplified, as core now has the functionality to generate UUIDs built-in.

**Comment by rmccue** [comment]
Oh, also, you said that. I failed comprehension at school.

**Comment by joehoyle** [comment]
Should we be adding some kind of migration wp-cli command for this too? Thinking if we import existing non-altis DBs, we'd want to update all GUIDS with real GUIDS?

**Comment by rmccue** [comment]
No, existing GUIDS should never change (half the problem with the existing ones is that they do when you have wp-cli imports).
