### ISSUE TITLE
Activate email doesn't use wp_mail_from

### ISSUE THREAD

**Issue by joehoyle** [humanmade/altis-cms#238]
It seems as though the email send for account activate "Activate $name" does not use the value from `apply_filters( 'wp_mail_from' )`, this means our overrides in altis-cloud don't work. It uses the value of `get_site_option( ‘admin_email’ );` and falls back to `$admin_email = 'support@' . $_SERVER['SERVER_NAME'];` which I think is not a good default for us. Atleast we could fallback to the wp_mail_from value.

props @stuartshields for digging into this.

**Comment by stuartshields** [comment]
Link to the line of code causing the issue:
https://github.com/WordPress/WordPress/blob/master/wp-includes/ms-functions.php#L952-L956

**Comment by roborourke** [comment]
Fixed in #249
