### ISSUE TITLE
Update to WordPress 5.5

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-cms#239]
Integration issue for WordPress 5.5, which is planned for August.

Notable things we need to account for:

* [Native lazy-loading](https://make.wordpress.org/core/2020/07/14/lazy-loading-images-in-5-5/) - Needs integration in Media with Gaussholder
* [CSS changes to buttons](https://make.wordpress.org/core/2020/07/10/new-css-styles-for-buttons-with-disabled-state-in-wp-5-5/) - Likely needs integration with CSS
* [Editor updates in 5.5](https://make.wordpress.org/core/2020/07/02/editor-features-for-wordpress-5-5-update/) - Some significant UI changes here I think
* [WP_ENVIRONMENT_TYPE](https://make.wordpress.org/core/2020/07/24/new-wp_get_environment_type-function-in-wordpress-5-5/)
* [Image editing](https://make.wordpress.org/core/2020/07/20/editing-images-in-the-block-editor/)

Likely more to note too.

**Comment by rmccue** [comment]
Some raw Gutenberg screenshots from updating with no further changes:

![Screenshot_2020-07-20 Edit Post ‹ Altis Demo — Altis(3)](https://user-images.githubusercontent.com/21655/87947094-c52c2380-ca9a-11ea-8d64-a90acd73a54a.jpg)

![Screenshot_2020-07-20 Edit Post ‹ Altis Demo — Altis(4)](https://user-images.githubusercontent.com/21655/87947036-b3e31700-ca9a-11ea-9260-834bd7ce6c31.jpg)

Additionally, the mobile and tablet "preview" views are completely broken for me, showing a contentless preview about 20px tall, unsure if that's from our code or not (didn't get a screenshot).

Looks like our colour scheme will need updating, and we need to integrate with the new Gutenberg toolbar styling. The experiments and publication checklist features look fine and shouldn't need changes.

IMO, the Gutenberg toolbar styling looks terrible, and it's also very jarring as a user to see it change. It may be worth considering whether we can revert the visual changes altogether.

**Comment by rmccue** [comment]
Related, Gutenberg changelog for 5.5: https://github.com/WordPress/gutenberg/issues/23669

**Comment by lachlanj** [comment]
> It may be worth considering whether we can revert the visual changes altogether.

I'm not sure if this is a serious consideration or just a frustration with the new changes but I would hope that we don't try to revert this. WordPress has changed it's UI many times over the years for better or worse, but personally I think mostly for the better. It would be a shame to have to deviate from this.

**Comment by roborourke** [comment]
REST API update is showing these warnings:

```
register_rest_route was called incorrectly. The REST API route definition for ... is missing the required permission_callback argument. For REST API routes that are intended to be public, use __return_true as the permission callback. Please see Debugging in WordPress for more information. (This message was added in version 5.5.0.)
```

This affects the following routes:

- `workflows/v1/webhooks/(?P[\w\-\.]+)\/(?P[\w\-\.]+)`
- `workflows/v1/notifications/(?P[\d]+)/(?P[\d]+)`
- `workflows/v1/notifications/(?P[\d]+)`
- `elasticpress/v1/pointer_search`
- `elasticpress/v1/pointer_preview`

**Comment by roborourke** [comment]
PR opened for Workflows, we may have to workaround the ElasticPress endpoint registry for now as I'm not sure when 3.5.0 which has the fix will ship.

**Comment by roborourke** [comment]
I looked into image editing, in short it sends rotation and crop data to the endpoint `/wp/v2/media/:id/edit` which handles the transformation and sends back a new attachment. While we could potentially hijack that endpoint and force it to return the same attachment with a modified URL containing the tachyon args there are 2 things standing in the way of that:

- Tachyon does not support rotating images via query string https://github.com/humanmade/tachyon/issues/123
- Smart media editor does not support creating a one-off custom crop unrelated to an image size https://github.com/humanmade/smart-media/issues/92

**Comment by roborourke** [comment]
Marking this as done, the gaussholder one can come later is indirectly related.
