### ISSUE TITLE
Rename "real GUIDs"

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-cms#240]
#237 introduced the "real GUIDs" code. This name originally comes from my [standalone plugin](https://github.com/rmccue/realguids) where it needed a name, but for Altis, it's basic functionality.

I'd recommend we move the two functions into the main namespace and remove the subnamespace altogether to eliminate the "real GUIDs" name. Ultimately, the user value we're delivering with this is to improve imports and exports in the future, and the functionality is not a feature itself.

**Comment by PriyaBhatia0210** [comment]
Closing as we wont do this.
