### ISSUE TITLE
Allow a feature-flag for real GUIDs

### ISSUE THREAD

**Issue by Nikschavan** [humanmade/altis-cms#258]
Real GUIDs were added in the PR https://github.com/humanmade/altis-cms/pull/237 but it looks like this is enabled by default.

We have a legacy code that relies on the WordPress generated GUIDs which will probably take some time to migrate and/or delay the upgrade to Altis v5.

We could also remove the filters added in the PR #237 but I think it would be much cleaner if there was a feature flag that could be just disabled?

**Comment by roborourke** [comment]
@Nikschavan so the legacy code is relying on GUIDs to be URLs? I can see that as an option for attachments but I'm generally not keen on the idea of of using GUIDs for this - they should never change and some features allow for attachment files to be replaced.

I'll discuss this with the team but I think your best option will be to use the filter as this use case is project specific. Or you could use the `post_name` or `post_title` fields instead.

For what it's worth I would like to do duplicate image detection but using a perceptual hash in future.

**Comment by roborourke** [comment]
@Nikschavan so it turns out that guids for attachments are not overridden by this feature so it's a non issue. We check for the existence of the guid first before setting it - for attachments WP sets this before our filter runs so all good 👍
