### ISSUE TITLE
Remove admin and network admin email addresses

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-cms#290]
The concept of the admin email in WP is outdated, let's remove it. "Admin" type things should be sent via the Altis Dashboard or support systems generally. We're also partially removing this concept already by removing the verification step.

**Comment by johnbillion** [comment]
FYI on the SW project the network admin email address is actively used for monitoring new user signups.

**Comment by rmccue** [comment]
Closing this as we never did do it.
