### ISSUE TITLE
Upgrade for WordPress 5.6

### ISSUE THREAD

**Issue by jennybeaumont** [humanmade/altis-cms#293]
We need to upgrade WordPress to 5.6.

- Known issue: required login feature

----

[Field guide](https://make.wordpress.org/core/2020/11/20/wordpress-5-6-field-guide/)

Dev notes:

* [REST API](https://make.wordpress.org/core/2020/12/08/rest-api-changes-in-wordpress-5-6/)
* [Editor](https://make.wordpress.org/core/2020/12/03/wordpress-5-6-core-editor-overview/)
* [Auto-updates](https://make.wordpress.org/core/2020/11/24/core-major-versions-auto-updates-ui-changes-in-wordpress-5-6-correction/)

**Comment by roborourke** [comment]
This is merged in now, I think we can handle the other items separately and during QA in Jan
