### ISSUE TITLE
Support dark mode in admin

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/altis-cms#309]
### Description

With the ubiquitous adoption of dark mode in web applications, it would be nice if the custom admin styles in the Altis WordPress admin supported dark mode.

### Notes
An MVP could be simply adding an additional admin color scheme that used darker colors vs. the lighter background that the existing styles used.

A future iteration could include support for OS-based light/dark mode settings.

Prior art exists for other dark mode implementation examples.

**Comment by rmccue** [comment]
Closing as won't do.
