### ISSUE TITLE
Add more default clonable post types and config support for post cloner

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-cms#313]
The post cloner feature has quite restricted defaults that aren't very useful out of the box and can cause some confusion.

The default clonable post type is just `post`, we should probably include all public post types, or least add pages and reusable blocks to the default list.

In addition it might be good to provide a way to configure the following via the module config:

- Clonable post types
- Clonable post statuses
- Clone capability

**Comment by rmccue** [comment]
We replaced the post cloner so closing out.
