### ISSUE TITLE
Wrong QUERY_STRING parsing can lead to endless redirections

### ISSUE THREAD

**Issue by igmoweb** [humanmade/altis-cms#315]
We faced a really hard to track issue in Batcache yesterday that was leading to a site redirecting forever. So take this URL as an example:

`site.com?whatever=&ignacio=true`

Note that the first argument, `whatever` is empty, however, it's suffixed with the `=` symbol. This leads WordPress to redirect to `site.com?whatever&ignacio=true` (Note now that the `=` is gone). For more information check this core file to see how the URL is parsed and rebuilt again without the equal symbol: https://github.com/WordPress/WordPress/blob/5.5.3/wp-includes/canonical.php#L533-L551

So back to Batcache, when this parses the URL, it generates a unique hash for that URL and stores it in `Batcache::keys` (see https://github.com/humanmade/batcache/blob/master/advanced-cache.php#L531-L557  and https://github.com/humanmade/batcache/blob/master/advanced-cache.php#L328-L331).

If cache redirections are enabled (recommended in our site), Batcache will store this URL as a redirected one with that hash. So now WordPress redirects to  `site.com?whatever&ignacio=true`  and Batcache considers that URL the same than the previous one, with the same hash, so it will redirect it, again and again, causing an endless redirect loop.

We had to add a small snippet to solve this:
```php
global $batcache;
if ( isset( $_SERVER['QUERY_STRING'] ) && strpos( $_SERVER['QUERY_STRING'], '=&' ) != false ) {
	$batcache['unique']['query'] = md5( $_SERVER['QUERY_STRING'] );
}
```

There are some things that make this one really hard to reproduce. The `$batcache->unique` property can change between those two URLs so the hash would change and the redirect doesn't happen. I haven't track it down yet as it requires much more time to do so but I'm happy to do so if needed.

Acceptance criteria:

- [ ] ...

**Comment by roborourke** [comment]
This was fixed in #301
