### ISSUE TITLE
Network enabling / disabling a theme causes an endless redirect loop

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-cms#328]
Steps to reproduce:
1. Ensure `$_SERVER['HTTP_REFERER'] = '';` as is the case on cloud envs
2. Try network enabling a theme
3. Endless redirect loop

This should just complete the action without issue. The problem is the exact same as the one fixed in #316 where we subsequent actions are dependent on the result of `wp_get_referer()`.

This would also become a non-issue if we implement #14.

Acceptance criteria:

- [ ] Network enabling / disabling a theme should not cause an endless redirect loop

Related core trac ticket https://core.trac.wordpress.org/ticket/52378

**Comment by roborourke** [comment]
Little addendum to this one - the network theme action links are generated using `wp_nonce_url()` which is unfilterable. This will require us to update the CloudFront rules to pass headers that are not used for calculating cache buckets to the web servers, then we can allow using the referer in authenticated requests.

For unauthenticated requests the referer should be set to empty.

**Comment by jennybeaumont** [comment]
Should be solved by https://app.zenhub.com/workspace/o/humanmade/terraform-app-stack/issues/794

**Comment by roborourke** [comment]
Just following up and this is now fixed! Thanks @wisyhambolu
