### ISSUE TITLE
PHP 7.4 errors in dependencies

### ISSUE THREAD

**Issue by faishal** [humanmade/altis-cms#336]
We found the following errors after running PHP 7.4 compatibility

- vendor/stuttter/wp-user-signups/wp-user-signups/includes/classes/class-wp-signup.php: 4 errors

  - [x] [170] : "$this" can no longer be used in a plain function or method since PHP 7.1. - PHPCompatibility.Variables.ForbiddenThisUseContexts.OutsideObjectContext

  - [x] [210] : "$this" can no longer be used in a plain function or method since PHP 7.1. - PHPCompatibility.Variables.ForbiddenThisUseContexts.OutsideObjectContext

  - [x] [222] : "$this" can no longer be used in a plain function or method since PHP 7.1. - PHPCompatibility.Variables.ForbiddenThisUseContexts.OutsideObjectContext

  - [x] [243] : "$this" can no longer be used in a plain function or method since PHP 7.1. - PHPCompatibility.Variables.ForbiddenThisUseContexts.OutsideObjectContext

- stuttter/wp-user-signups/wp-signups/includes/classes/class-wp-signup.php: 4 errors

  - [ ] [162] : "$this" can no longer be used in a plain function or method since PHP 7.1. - PHPCompatibility.Variables.ForbiddenThisUseContexts.OutsideObjectContext

  - [ ] [202] : "$this" can no longer be used in a plain function or method since PHP 7.1. - PHPCompatibility.Variables.ForbiddenThisUseContexts.OutsideObjectContext

  - [ ] [214] : "$this" can no longer be used in a plain function or method since PHP 7.1. - PHPCompatibility.Variables.ForbiddenThisUseContexts.OutsideObjectContext

  - [ ] [235] : "$this" can no longer be used in a plain function or method since PHP 7.1. - PHPCompatibility.Variables.ForbiddenThisUseContexts.OutsideObjectContext

**Comment by jazzsequence** [comment]
We currently have the latest version of WP User Signups and the release notes for the version (which was released almost a year ago) indicates that it was updated to add PHP 7.3 support.

I opened a new ticket over there to just track PHP 7.4 compatibility and so we have something to add a PR against if we contribute the development on this. https://github.com/stuttter/wp-user-signups/issues/11

**Comment by roborourke** [comment]
So the problems appear to be duplicated, the only difference is the path eg. `vendor/stutter` vs `stuttter` and the line numbers, as Altis v4 is using the latest version we ignore the latter 4 items. Presumably it's referencing an older version active in the one v3 project.

PR is up here https://github.com/stuttter/wp-user-signups/pull/12

**Comment by roborourke** [comment]
PR has been merged and 5.0.1 release cut :) I've updated the CMS module and made releases.
