### ISSUE TITLE
Simplify rewrite rule flushing

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/altis-cms#355]
When rewrite rules are flushed (either via WP-CLI or in the admin by re-saving permalinks), it doesn't actually flush the cache, requiring a second step to also flush the WordPress cache if rewrites have been updated/changed. Expected behavior is for this to just work, without having to remember to force an object cache flush as well.

Suggested via https://humanmade.zendesk.com/agent/tickets/4774

**Acceptance criteria:**

- [ ] ...

**Dev notes**

* One of the things that `flush_rewrite_rules` actually does is update the option `rewrite_rules` with an empty string.
* You can potentially use `update_option_rewrite_rules` to hook in after that option has been updated.

https://developer.wordpress.org/reference/classes/wp_rewrite/flush_rules/
https://developer.wordpress.org/reference/hooks/update_option_option/

**Comment by rmccue** [comment]
I haven't heard this happening to anyone recently, so closing out.
