### ISSUE TITLE
Increase the admin toolbar hover contrast

### ISSUE THREAD

**Issue by johnbillion** [humanmade/altis-cms#359]
When hovering over an admin toolbar menu item, the change in colour is barely noticeable. It changes from very light grey to white, whereas vanilla WP changes from grey to blue on hover.

It would be good if this hover colour had greater contrast with the link colour.

## Altis

<img width="142" alt="" src="https://user-images.githubusercontent.com/208434/113710886-90253700-96e4-11eb-8239-f1c4f48830ef.png">

## Vanilla WP

<img width="152" alt="" src="https://user-images.githubusercontent.com/208434/113710957-a7642480-96e4-11eb-86f6-6436785f1393.png">

**Comment by roborourke** [comment]
Fixed in #506
