### ISSUE TITLE
Cloned posts don't update the permalink entirely

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/altis-cms#367]
Cloned posts don't necessarily update the permalink fully. After a post is cloned the URL does not necessarily match with the cloned slug, which causes a 404 error if you try to view the post. 

Clicking in Quick Edit will show the slug with `-cloned` appended to the end, but the actual `View` link still points to the old URL.

Steps to reproduce:
1. Create and publish a post
2. Clone that post and publish the clone
3. The cloned post will 404 when viewed
4. The URL and slug will not match.

Expected behavior:
Cloned posts have entirely unique URLs and do not 404.

![Screen Shot 2021-04-16 at 11 49 44 AM](https://user-images.githubusercontent.com/991511/115064757-8d77ce00-9eaa-11eb-8d52-7b4fa9bdc0b2.png)
![Screen Shot 2021-04-16 at 11 49 20 AM](https://user-images.githubusercontent.com/991511/115064766-8ea8fb00-9eaa-11eb-96b1-6481ca646dd0.png)

related to product-dev#706

Acceptance criteria:

- [ ] ...

**Comment by johnbillion** [comment]
Is this an issue for https://github.com/humanmade/post-cloner?

**Comment by jazzsequence** [comment]
@johnbillion Probably, but the Post Cloner plugin isn't (yet) part of our ZenHub board so, partially for visibility, I put the ticket in the Altis CMS repo. Also, I haven't tested the issue outside the context of Altis, so there's a chance it's not actually the plugin but some integration, however I strongly suspect the issue to be triggered when the duplicate post is being created, which is most likely coming from the plugin.

**Comment by roborourke** [comment]
It's the `class-rewrites.php` part of the post cloner plugin, I think it would only ever work for sites with the post ID in the permalink because the way it messes with post URLs couldn't work otherwise. That behaviour should be opt-in or we should check for `%postid%` in the permalink structure of the current post type before letting that class modify URLs.
