### ISSUE TITLE
Remove starter content?

### ISSUE THREAD

**Issue by joehoyle** [humanmade/altis-cms#38]
Currently we get Hello World / Privacy page / comments by default, we could disable those.

**Comment by rmccue** [comment]
IMO, we should have a completely custom `install.php` for this.

**Comment by roborourke** [comment]
What's the purpose / benefit of removing this default content?

For clean install it helps to see _something_ to get started with. Typically the next step after getting a site set up is to import existing content or a db so I'm not seeing any benefit to this personally unless we're replacing the default content with helpful links to docs and perhaps examples of any built in features like experience blocks in future.

**Comment by roborourke** [comment]
Closing as a better solution would to be make better / more Altis specific starter content. Very limited value added versus required effort to remove this.
