### ISSUE TITLE
Document RSS feed locations

### ISSUE THREAD

**Issue by sambulance** [humanmade/altis-cms#393]
We have a page on [configuring RSS feeds](https://docs.altis-dxp.com/cms/rss/) from a Altis perspective, but there is no information on where to find these feeds. It would be useful to expand the information here a bit more. 

I'm opening a ticket as I a bit of guidance on the best way to add this. I was going to open a PR to add a link to the [WordPress documentation on feeds](https://wordpress.org/support/article/wordpress-feeds/) as we are using default WP behaviour (I believe?). Would that be acceptable? Or should we add more information on-page? How do we handle documenting default WP features?

**Comment by rmccue** [comment]
I think linking out is better than nothing, so let's start there. Generally, we don't re-document WP things, but given we have an RSS feeds config page, it makes sense for add additional stuff there.

**Comment by sambulance** [comment]
Opened #394.

**Comment by rmccue** [comment]
Closing as fixed.
