### ISSUE TITLE
Fatal error on widgets screen

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-cms#439]
<img width="686" alt="Screen Shot 2021-10-12 at 12 05 27" src="https://user-images.githubusercontent.com/21655/136944677-599b61d7-ee2d-455a-8226-b65360b9ff7d.png">

This is https://github.com/humanmade/authorship/issues/84 

Steps to reproduce:
1. Go to Widgets page

Acceptance criteria:

- [ ] Viewing widgets page works and does not produce a fatal error

**Comment by robindevitt** [comment]
I'm struggling to replicate the issue.

When I view the Widgets page I am not seeing a fatal error
![Screenshot 2021-11-09 at 14 42 41](https://user-images.githubusercontent.com/16571365/140926743-7c276914-7618-479f-8227-126e16f25ef0.png)

**Comment by roborourke** [comment]
@robindevitt you might need to check an older version of Altis, I don't think v9 with WordPress 5.8 was available at the time.

**Comment by robindevitt** [comment]
@roborourke is that based on the comment from [Fatal error in customizer #84](https://github.com/humanmade/authorship/issues/84)? I notice there that the issue was also found on [Altis v9 beta](https://github.com/humanmade/authorship/issues/84#issuecomment-940905141).

**Comment by roborourke** [comment]
Ah, so there's a PR attached to that issue you linked, it's been merged and it's part of the 0.2.9 release here https://github.com/humanmade/authorship/releases/tag/0.2.9

We track patch versions of the authorship dependency so this is fixed, by the @rmccue himself!
