### ISSUE TITLE
Add config to disable XMLRPC

### ISSUE THREAD

**Issue by joehoyle** [humanmade/altis-cms#46]
I think we should disable xmlrpc.php by default, unless enabled, thoughts?

**Comment by rmccue** [comment]
I'd say no, primarily because it'll break the mobile apps, and we probably shouldn't break those by default. We already have rate-limiting, so don't think we really gain much.

**Comment by rmccue** [comment]
@joehoyle to update ticket to clarify intent.

**Comment by joehoyle** [comment]
Ok - how about a CMS setting for `xmlrpc` => true / false?
