### ISSUE TITLE
"Reusable blocks" should be Title Case in the sidebar

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-cms#475]
Steps to reproduce:
1. Open Altis admin panel
2. Observe "Reusable blocks" in sidebar

Title should be "Reusable Blocks"

<img width="169" alt="CleanShot 2021-11-11 at 13 11 15@2x" src="https://user-images.githubusercontent.com/21655/141303991-b062f19c-308a-47b6-9cd0-29ad8d3e4601.png">

Acceptance criteria:

- [ ] Link in admin menu should be "Reusable Blocks" with uppercase "B"

**Comment by robindevitt** [comment]
[PR](https://github.com/humanmade/altis-cms/issues/475) is ready for review and been requested by Rob or Shadi

**Comment by robindevitt** [comment]
This has been closed and [released](https://github.com/humanmade/altis-reusable-blocks/releases/tag/v0.2.1)
