### ISSUE TITLE
Editing Reusable block shows null in parent category dropdown

### ISSUE THREAD

**Issue by mikelittle** [humanmade/altis-cms#535]
When editing a reusable block, the word "null" appears in the drop down list of potential parent categories.
![Screenshot_2022-02-22_at_17_24_27.png](https://images.zenhubusercontent.com/5833067cb9dc3c622022491e/36711e9b-117b-48fe-8c99-f82f912dfc28)

**Comment by roborourke** [comment]
Fixed by https://github.com/humanmade/altis-reusable-blocks/pull/33
