### ISSUE TITLE
Reusable blocks error

### ISSUE THREAD

**Issue by mikelittle** [humanmade/altis-cms#536]
I broke the reusable blocks!

Steps to reproduce:

I had a three reusable blocks (which still display on the pages where they are used.
I clicked to edit one of them I then clicked on the relationships icon in the sidebar. This displayed "no relationships" even though the block is used in a page. (I was actually trying to recreate this to report it.) 
I then clicked on the A/B icon in the side bar. I got the "The editor has encountered an unexpected error" error.

Clicking the "Attempt recovery" button gives a blank pages (sidebar and top bar are still displayed)

Here is the "post text" (from the "Copy post text" button)
```
<!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:image {"id":16,"width":359,"height":269,"sizeSlug":"medium","linkDestination":"none"} -->
<figure class="wp-block-image size-medium is-resized"><img src="https://demo.altis.cloud/tachyon/sites/76/2022/02/cheese-Shropshire_Blue.jpg?fit=300%2C300" alt="" class="wp-image-16" width="359" height="269"/></figure>
<!-- /wp:image --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:heading {"level":4} -->
<h4>I love cheese</h4>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>I love cheese, especially boursin. Stilton cheddar cheesy feet paneer cut the cheese emmental cheesy grin. Cheesecake st. agur blue cheese. Cheese triangles when the cheese comes out everybody's happy chalk and cheese.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->
```

and the "Error text" (from the "Copy error" button)

```
TypeError: Cannot read properties of undefined (reading 'started')
    at https://mikedemo.demo.altis.cloud/vendor/altis/aws-analytics/build/experiments/sidebar.93c2ee4a.js?ver=5.8.3:1:18215
    at we (https://mikedemo.demo.altis.cloud/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:84:293)
    at zj (https://mikedemo.demo.altis.cloud/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:226:496)
    at Th (https://mikedemo.demo.altis.cloud/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:152:223)
    at tj (https://mikedemo.demo.altis.cloud/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:152:152)
    at Te (https://mikedemo.demo.altis.cloud/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:146:151)
    at https://mikedemo.demo.altis.cloud/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:61:68
    at unstable_runWithPriority (https://mikedemo.demo.altis.cloud/wp-includes/js/dist/vendor/react.min.js?ver=16.13.1:25:260)
    at Da (https://mikedemo.demo.altis.cloud/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:60:280)
    at Pg (https://mikedemo.demo.altis.cloud/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:61:14)
```

Note this seems to be a permanent error? Refreshing the page didn't fix it. Logging out, clearing cookies, and logging in again didn't fix it either. All reusable blocks on the list of reusable blocks exhibit the same error.

![Banners_and_Alerts_and_Edit_Reusable_block_‹_Altis_Demo_Site_—_Altis.png](https://images.zenhubusercontent.com/5833067cb9dc3c622022491e/f2922508-8e91-4a9c-a61d-0a229faafa53)

From the browser console:
![Banners_and_Alerts_and_Edit_Reusable_block_‹_Altis_Demo_Site_—_Altis.png](https://images.zenhubusercontent.com/5833067cb9dc3c622022491e/004f458f-1eae-4ac2-865c-e4841736985c) 

That 403 url is 
```
https://mikedemo.demo.altis.cloud/wp-json/altis-reusable-blocks/v1/relationships?block_id=15&page=1&_locale=user
```

I don't know if this is a core WP issue or realted to how we expose the reusable blocks.

Acceptance criteria:

- [ ] ...

**Comment by mikelittle** [comment]
Update: Clearing local storage resolves this but we are somehow storing something invalid as soon as he A/B icon is clicked..

**Comment by robindevitt** [comment]
Started looking into this issue, during my efforts of trying to replicate the issue I had no success. However when I clicked A/B experiments tab I was able to trigger the same errors mentioned above.

I found it to only happen on the Reusable Blocks post type screen.

![Screenshot 2022-03-11 at 15.54.52.png](https://images.zenhubusercontent.com/615d863972ceea502ec6a54f/1678b5b8-18d5-4d4a-8664-46c587341d70)

**Comment by robindevitt** [comment]
Based on @mikelittle's comment of clearing the local storage resolves the issue.

With a working Reusable block I determined which key/value is breaking the page.

The key I determined to break the page is `WP_DATA_USER_*`. ( * is the user's ID, eg: `WP_DATA_USER_1`, `WP_DATA_USER_2` )

I have then saved the value and then clicked the A/B Experience tab to generate the error.

I copied the value for the key `WP_DATA_USER_*` from the local storage.

Once I had the two values I then compared them.

Before clicking the A/B experience tab
```
   "core/interface":{
      "enableItems":{
         "singleEnableItems":{
            "complementaryArea":{
               "core/edit-post":"edit-post/document"
            }
         }
      }
   }
```

After clicking the A/B experience tab
```
   "core/interface":{
      "enableItems":{
         "singleEnableItems":{
            "complementaryArea":{
               "core/edit-posts":"altis-analytics/altis-experiments"
            }
         }
      }
   }
```

**Comment by mikelittle** [comment]
Is that a typo? `core/edit-post` vs `core/edit-posts`

**Comment by robindevitt** [comment]
> Is that a typo? core/edit-post vs core/edit-posts

Thanks @mikelittle, that indeed was a typo, original comment has been updated.

**Comment by mikelittle** [comment]
ah. I thought that might have between the actual bug!🙁

**Comment by robindevitt** [comment]
Currently I don't think what I have pointed out is exactly the bug, but more so the findings as I have gone through the issue.

**Comment by robindevitt** [comment]
Current PR is a work in progress. 

I was able to replicate the issue and pinpoint the error being caused by experiments not supported by certain post types.

The solution will be preventing adding experiments to post types if they are not supported.
