### ISSUE TITLE
Simple Local Avatar Missing JS file

### ISSUE THREAD

**Issue by mikelittle** [humanmade/altis-cms#617]
The version of 10Up's Simple Local Avatar we use has a JavaScript file missing. Because of changes in the plugin, it now expects to find it's JS file in a built `dist` folder. 

![Screenshot 2022-07-14 at 18.05.16.png](https://images.zenhubusercontent.com/5833067cb9dc3c622022491e/17ff7e4a-9837-480f-826d-847d37e9040e)

The git repo does not have that by default. This change seemed to arrive in version 2.2.0. The current version from the git repo, 2.5.0, has the same issue. The download from wp.org does not.

This means you cannot use the functionality form the profile page.

Possible solutions:
- Include a build step in the downloaded repo to generate the `dist` folder. Ugh! No!
- Fork the repo and add the built assets to it. 
- Require the plugin from wpackagist but still move it to the vendor folder.

**Comment by roborourke** [comment]
wpackagist is not an option unfortunately, also forking is not strictly required, it's a significant maintenance burden. For ElasticPress when this happened I just added the built plugin from wp.org directly to the search module repo under a `/lib` directory and included it from there.

**Comment by kovshenin** [comment]
> wpackagist is not an option unfortunately

Couldn't quickly find previous discussions about this. Just curious why not?

Also:

* Added a PR to bundle 2.5.0 from WordPress.org in lib.
* Opened upstream: https://github.com/10up/simple-local-avatars/issues/144

**Comment by roborourke** [comment]
@kovshenin The "repositories" property is a root-only property so will be ignored in packages like the modules, can only be added in the root project composer.json. We don't have it as a requirement although we could technically force it. There's a bit of background here https://github.com/humanmade/altis-skeleton/issues/20
