### ISSUE TITLE
Extra wide featured image renders incorrectly in the editor

### ISSUE THREAD

**Issue by mikelittle** [humanmade/altis-cms#626]
An extra wide (2048 x 597) featured image selected from the Global media library renders as a square thumbnail overlaying the block editor controls.

Steps to reproduce:
1. Upload a wide image (2048 x 597) toi the global media library
2. Select that image as a featured image on a page in Twenty Twentytwo theme
3. Observe the image in the block editor shows as a square thumbnail overlaying the editor controls.

The image should render in correct proportions without overlaying the controls.

![Screenshot 2022-08-02 at 18.02.59.png](https://images.zenhubusercontent.com/5833067cb9dc3c622022491e/e5457f8e-abb5-4019-9620-2d4e12af5902)

Acceptance criteria:

- [ ] ...

**Comment by roborourke** [comment]
Is this only when selecting an image from the global media library? Or does it happen for local images too?

**Comment by robindevitt** [comment]
@mikelittle I have tested this using images from the local and global media libraries and can't replicate it. do you have any further steps to replicate it?

**Comment by mikelittle** [comment]
How wide was your image? I'll attach the one used.
![skyline-2048x590](https://user-images.githubusercontent.com/358499/182653620-6523db5d-ad42-49c6-8d59-78d2006a7555.jpg)

**Comment by robindevitt** [comment]
Thanks @mikelittle I have been able to replicate the issue with your image supplied.

It's weird, there is a `span` that gets some padding added to it inline. Other images that render correctly the padding is a fixes value of 150px. With this image/size the padding is a `28.8086%`.

**Comment by robindevitt** [comment]
Moving this back to backlog and picking up other `Must Haves` in V12 Manual QA (with PHP 8) #963

**Comment by robindevitt** [comment]
The "issue" appears to be caused where the image url has this`?resize=150%2C150&crop_strategy=smart` appended to the image URL. Removing the string from the URL renders the original cropped image and all is displayed correctly. 

So it appears that the image is being read based on it's original sized image and not the image with the above string.

**Comment by roborourke** [comment]
So the right crop is coming back, maybe it's taking a while to generate or there's incorrect metadata with regards to its dimensions being generated.

I'd look into the logic that causes that different padding value to be added, and trace it back to the data being returned from the API to look for anything unexpected.

**Comment by robindevitt** [comment]
The padding appears to be added in WordPress Core through this below function with the `imageStyle` const.

```javascript
function ResponsiveWrapper(_ref) {
  let {
    naturalWidth,
    naturalHeight,
    children,
    isInline = false
  } = _ref;
  const [containerResizeListener, {
    width: containerWidth
  }] = Object(external_wp_compose_["useResizeObserver"])();

  if (external_wp_element_["Children"].count(children) !== 1) {
    return null;
  }

  const imageStyle = {
    paddingBottom: naturalWidth < containerWidth ? naturalHeight : naturalHeight / naturalWidth * 100 + '%'
  };
  const TagName = isInline ? 'span' : 'div';
  return Object(external_wp_element_["createElement"])(TagName, {
    className: "components-responsive-wrapper"
  }, containerResizeListener, Object(external_wp_element_["createElement"])(TagName, {
    style: imageStyle
  }), Object(external_wp_element_["cloneElement"])(children, {
    className: classnames_default()('components-responsive-wrapper__content', children.props.className)
  }));
}
```

**Comment by robindevitt** [comment]
Using other images everything is rendered correctly, even with the thumbnail it is rendered correctly. Something specific around the image size and not so much images from the global media library.

**Comment by robindevitt** [comment]
> For some reason the naturalHeight and naturalWidth properties are being incorrectly calculated. Is there some other logic up the chain that determines whether the responsive wrapper is used, or can we see where and how those properties are being defined?

I have been looking into this, it's not exactly clear from what I have seen.

> Are you saying this happens with the very wide image even it comes from the standard media library?

It's not happening if with the same size image from the standard media library.

If I disable `tachyon` in the `composer.json` there is no issue rendering the image.

**Comment by robindevitt** [comment]
So I have gone and set a featured image from the standard library as well as the global library, I then got the image meta and noticed that the images from the standard library have an extra meta key, `_tachyon_dynamic` and the value is `true`. Where as the image from the global library doesn't.

Could this be the missing piece?

**Comment by roborourke** [comment]
Hmm, unlikely. I'd look at the nested properties like sizes, compare the url, width, height properties etc...

**Comment by robindevitt** [comment]
Thanks for that @roborourke and gave me some thought around this too and some further testing.

If I use the `Twenty Nineteen` or `Twenty Twenty` theme then there is no issue. 

This appears to occur with `Twenty Twenty-Two` enabled.

Comparing the meta for the image between the two the information is pretty much identical except for that Twenty Twenty images sizes there are 6 and Twenty Twenty Two there are 4 sizes.

Twenty Twenty
- The image `sizes` array has 6

Meta below:
```php
array(6) {
  ["image_meta"]=> array(11) {
    ["aperture"]=> string(1) "0"
    ["credit"]=> string(0) ""
    ["camera"]=> string(0) ""
    ["caption"]=> string(0) ""
    ["created_timestamp"]=> string(1) "0"
    ["copyright"]=> string(0) ""
    ["focal_length"]=> string(1) "0"
    ["iso"]=> string(1) "0"
    ["shutter_speed"]=> string(1) "0"
    ["title"]=> string(0) ""
    ["orientation"]=> string(1) "1"
  }
  ["filesize"]=> string(6) "273979"
  ["file"]=> string(40) "verticz-squencz-HAmKh06RZb0-unsplash.jpg"
  ["width"]=> int(2048)
  ["height"]=> int(590)
  ["sizes"]=> array(6) {
    ["thumbnail"]=> array(4) {
      ["file"]=> string(92) "https://altis-v12.altis.dev/tachyon/sites/2/2022/09/verticz-squencz-HAmKh06RZb0-unsplash.jpg"
      ["width"]=> int(2048)
      ["height"]=> int(590)
      ["mime-type"]=> string(10) "image/jpeg"
    }
    ["medium"]=> array(4) {
      ["file"]=> string(92) "https://altis-v12.altis.dev/tachyon/sites/2/2022/09/verticz-squencz-HAmKh06RZb0-unsplash.jpg"
      ["width"]=> int(2048)
      ["height"]=> int(590)
      ["mime-type"]=> string(10) "image/jpeg"
    }
    ["medium_large"]=> array(4) {
      ["file"]=> string(92) "https://altis-v12.altis.dev/tachyon/sites/2/2022/09/verticz-squencz-HAmKh06RZb0-unsplash.jpg"
      ["width"]=> int(2048)
      ["height"]=> int(590)
      ["mime-type"]=> string(10) "image/jpeg"
    }
    ["large"]=> array(4) {
      ["file"]=> string(92) "https://altis-v12.altis.dev/tachyon/sites/2/2022/09/verticz-squencz-HAmKh06RZb0-unsplash.jpg"
      ["width"]=> int(2048)
      ["height"]=> int(590)
      ["mime-type"]=> string(10) "image/jpeg"
    }
    ["post-thumbnail"]=> array(4) {
      ["file"]=> string(92) "https://altis-v12.altis.dev/tachyon/sites/2/2022/09/verticz-squencz-HAmKh06RZb0-unsplash.jpg"
      ["width"]=> int(2048)
      ["height"]=> int(590)
      ["mime-type"]=> string(10) "image/jpeg"
    }
    ["twentytwenty-fullscreen"]=> array(4) {
      ["file"]=> string(92) "https://altis-v12.altis.dev/tachyon/sites/2/2022/09/verticz-squencz-HAmKh06RZb0-unsplash.jpg"
      ["width"]=> int(2048)
      ["height"]=> int(590)
      ["mime-type"]=> string(10) "image/jpeg"
    }
  }
}
```

Twenty Twenty-Two
- The image `sizes` array has 4

Meta below:
```php
array(6) {
  ["image_meta"]=> array(11) {
    ["aperture"]=> string(1) "0"
    ["credit"]=> string(0) ""
    ["camera"]=> string(0) ""
    ["caption"]=> string(0) ""
    ["created_timestamp"]=> string(1) "0"
    ["copyright"]=> string(0) ""
    ["focal_length"]=> string(1) "0"
    ["iso"]=>string(1) "0"
    ["shutter_speed"]=> string(1) "0"
    ["title"]=> string(0) ""
    ["orientation"]=> string(1) "1"
  }
  ["filesize"]=> string(6) "273979"
  ["file"]=> string(40) "verticz-squencz-HAmKh06RZb0-unsplash.jpg"
  ["width"]=> int(2048)
  ["height"]=> int(590)
  ["sizes"]=> array(4) {
    ["thumbnail"]=> array(4) {
      ["file"]=> string(92) "https://altis-v12.altis.dev/tachyon/sites/2/2022/09/verticz-squencz-HAmKh06RZb0-unsplash.jpg"
      ["width"]=> int(2048)
      ["height"]=> int(590)
      ["mime-type"]=> string(10) "image/jpeg"
    }
    ["medium"]=> array(4) {
      ["file"]=> string(92) "https://altis-v12.altis.dev/tachyon/sites/2/2022/09/verticz-squencz-HAmKh06RZb0-unsplash.jpg"
      ["width"]=> int(2048)
      ["height"]=> int(590)
      ["mime-type"]=> string(10) "image/jpeg"
    }
    ["medium_large"]=> array(4) {
      ["file"]=> string(92) "https://altis-v12.altis.dev/tachyon/sites/2/2022/09/verticz-squencz-HAmKh06RZb0-unsplash.jpg"
      ["width"]=> int(2048)
      ["height"]=> int(590)
      ["mime-type"]=> string(10) "image/jpeg"
    }
    ["large"]=> array(4) {
      ["file"]=> string(92) "https://altis-v12.altis.dev/tachyon/sites/2/2022/09/verticz-squencz-HAmKh06RZb0-unsplash.jpg"
      ["width"]=> int(2048)
      ["height"]=> int(590)
      ["mime-type"]=> string(10) "image/jpeg"
    }
  }
}

**Comment by roborourke** [comment]
That's not too surprising - themes can register as many different image sizes as they like. I think what might be interesting here is that twenty twenty two has the `post-thumbnail` image size which a special feature set via [`set_post_thumbnail_size()`](https://developer.wordpress.org/reference/functions/set_post_thumbnail_size/) and `add_theme_support( 'post-thumbnails' )`.

It might be to do with the size / handling of that, assuming that's what gets used when picking the featured image for display in the sidebar.

**Comment by robindevitt** [comment]
All the images are essentially the same size based on the `width`, `height` and `file`.

So in the reported issue, the block is receiving the image in the "full' size from the library, making the relevant padding adjustments needed, but then showing the image with the extra info, `?resize=150%2C150&crop_strategy=smart` and not adjusting the padding according.

**Comment by roborourke** [comment]
Tachyon URLs always reference the original image - the query string arguments control the sizing etc... so `?resize=150,150` is actually the registered `thumbnail` size.

**Comment by robindevitt** [comment]
I have tried setting the thumbnail size with `set_post_thumbnail_size()` and I get mixed results.

If I use `set_post_thumbnail_size( 1200, 9999 );` then this appears as expected and the padding is appropriate. This is similar to the old themes.

However if I use `set_post_thumbnail_size( 150, 150 );` this the image is cropped down to fit that size, if I use `set_post_thumbnail_size( 150, 150, true );` the image shows as the square but the padding is still showing the same as when the issue doesn't occur. ie, the padding is being set appropriately for the image.

**Comment by robindevitt** [comment]
An image from the standard library works perfectly fine with the image `size` and `crop_strategy` being adhered to. Soon as the image is used from the global library that info seems to be ignored and the calculations are being made based on the original image URL.

I'm completely stumped by this bug now. @roborourke do you have any suggestions on this that I could be missing?

**Comment by roborourke** [comment]
Might be related to how the resizing is set up in the asset manager framework then. There’s a class in this repo that determines how the URL from the global site is built

**Comment by robindevitt** [comment]
Pr has been merged.
