### ISSUE TITLE
Update WordPress requirement to 6.0.1

### ISSUE THREAD

**Issue by kovshenin** [humanmade/altis-cms#627]
WordPress 6.0 is currently planned to be included in v13. Bump the requirement and make sure installation works as expected.

### Acceptance criteria

- [x] Merge https://github.com/humanmade/altis-cms/pull/603
- [x] Make sure WordPress 6.0.1 is installed when installing from scratch, or upgraded to when upgrading an existing Altis installation

**Comment by kovshenin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Vulcan-6284e0dfb386b00c83981426/issues/humanmade/altis-cms/627?planning-poker) with ZenHub @ferschubert-hm @jerico @mikelittle @wisyhambolu

**Comment by CStukey** [comment]
NOTE: Mike has identified a number of bugs with 6.0. Change in behavior re: query. Please keep in mind.
Details included in release notes.

**Comment by CStukey** [comment]
@jerico This ticket was refined and estimated during the Aug 10 refinement meeting.

**Comment by kovshenin** [comment]
All working as expected, closing issue.
