### ISSUE TITLE
Add config option for subdomain / subfolder multisite install

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-cms#69]
We should add a config option that allows setting whether the multisite is a subdomain or subfolder install by defining the `SUBDOMAIN_INSTALL` constant.

**Comment by joehoyle** [comment]
Is WP either or now? I thought you could actually just have both, it's really only the admin UI that is the blocker?

**Comment by rmccue** [comment]
Yeah; Rob went through it to double-check, and it really only affects the UI and one spot in the rewrites. We can tackle this by reworking the new site screen I think.

**Comment by rmccue** [comment]
Punting from 2.0 as unlikely we'll get to it.

**Comment by rmccue** [comment]
This is obsoleted by #50 I believe.
