### ISSUE TITLE
Add user avatar upload

### ISSUE THREAD

**Issue by joehoyle** [humanmade/altis-cms#7]
This is to upload an avatar in the website without having to go to Gravatar to change it. 

Work in progress here: #111 

Acceptance criteria:

- [x] Add the simple local avatars plugin
- [x] Ensure the plugin is added to the 'install overrides' list
- [x] Add a config option to enable / disable the plugin
- [x] Document the config option

**Comment by rmccue** [comment]
We can probably use 10up's for this: https://github.com/10up/simple-local-avatars

**Comment by pdewouters** [comment]
Just waiting on it to be published to packagist

**Comment by rmccue** [comment]
Now up on Packagist: https://packagist.org/packages/10up/simple-local-avatars

**Comment by pdewouters** [comment]
This is just blocked by https://github.com/10up/simple-local-avatars/pull/34

**Comment by adamsilverstein** [comment]
https://github.com/10up/simple-local-avatars/pull/34 is merged and milestoned for the 2.2 release.

**Comment by rmccue** [comment]
Thanks @adamsilverstein! 🤝
