### ISSUE TITLE
Hide Welcome popup

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-cms#74]
Reported by @ShinichiNishikawa - the standard WP welcome popup isn't really needed.

**Comment by rmccue** [comment]
We should think about whether we want to completely replace/redesign the dashboard experience (cc @humanmade/design). For 1.0.1 we can just turn it off though.

**Comment by roborourke** [comment]
Yeah we do - kept the focus of this ticket intentionally narrow.
