### ISSUE TITLE
Remove WP news feed dashboard meta box

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-cms#75]
We'll replace this with Altis related news in future.

**Comment by joeleenk** [comment]
I think this is done already:
https://github.com/humanmade/altis-cms/blob/134943e2d32247fe14db6cfe32aedc2599361c7d/inc/branding/namespace.php#L52

Or is this issue for creating the Altis news box?

**Comment by roborourke** [comment]
@joeleenk ah I didn’t realise that. Sorry, will close this and create a new issue for the Altis news one
