### ISSUE TITLE
Hide upgrade failed nag message

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-cms#85]
The platform-test site is currently showing a message saying "An automated WordPress update has failed to complete - please attempt the update again now."

This is reading in the `auto_core_update_failed` network option; unsure how this gets set, but we should hide this message in any case, as it's not user-actionable.

**Comment by rmccue** [comment]
Think this may be sorted.

**Comment by joehoyle** [comment]
Pretty sure this isn't fixed.
