### ISSUE TITLE
Improve Reusable Block interface: Integrate the Altis Reusable Blocks plugin 

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-cms#95]
Displays more information about reusable blocks. We may want to include this, or copy the code as it's quite small.

Add and test integration of the following Plugin:
https://github.com/humanmade/altis-reusable-blocks

- [x] Remove the existing reusable block code
- [x] Add code to load in this plugin

**Comment by roborourke** [comment]
I think copying the code is going to be easiest for our purposes. We can make any updates etc that we need to more quickly then

**Comment by rmccue** [comment]
I'm guessing @kevinlangleyjr's work on https://github.com/humanmade/altis-reusable-blocks will replace this?

**Comment by roborourke** [comment]
Ah yeah, Than mentioned that - I hadn't seen it yet. @kevinlangleyjr does this replace the functionality in the Fabrica one? I know it adds a bunch of stuff around the search. The reusable blocks post list table showing the number of instances and the secondary listing showing posts they're used on is pretty useful I think.

**Comment by meeware** [comment]
Is the Altis Reusable Blocks work the same (or related to) Extended Reusable Blocks that's under development on News (cc @tfrommen )?

**Comment by kevinlangleyjr** [comment]
I was planning on writing something up tomorrow when I was allocated to Altis to describe the similarities and differences between what I've been working on and the `Fabrica Reusable Block Instances` plugin. `altis-reusable-blocks` covers all the features offered in fabrica, but IMHO it does it better. I've also created a new UI to discover, filter, and select reusable blocks.

The codebase is related to the work I did for News on Enhanced Reusable Blocks, but it has been modified to fit better in the Altis environment. I also see the future features of `Altis Reusable Blocks` and `Enhanced Reusable Blocks` diverging greatly as development continues. Therefore, I created a new codebase and have adopted it to fit better in the Altis environment.

On Friday I will write an issue up proposing we integrate Altis Reusable Blocks into `altis-cms` and I'll provide much more information on the plugin at that time. 👍

**Comment by roborourke** [comment]
Sounds great, thanks @kevinlangleyjr!

**Comment by meeware** [comment]
Really appreciate the clarity of the explanation, thanks @kevinlangleyjr

**Comment by roborourke** [comment]
Renamed this to remove the reference to Fabrica and made it more generic.
